### ISSUE TITLE
Missing consumption values for some hours

### ISSUE THREAD

**Issue by CofkoCof** [cjaliaga/home-assistant-aquarea#75] opened 2024-01-02 09:58 UTC
Hi,

Really appreciate the work you put into this. I have upgraded the integration which now supports consumptions, but when added to HA, the values for consumptions are missing (always for the same hours). The values from consumption just stay the same and don't increase in some hour periods. Do you know what that is? Have I configured something wrong?

![2024-01-02_10h54_33](https://github.com/cjaliaga/home-assistant-aquarea/assets/48807086/2fa07a30-f363-47d6-a5ec-27c6f665817f)

![2024-01-02_10h55_05](https://github.com/cjaliaga/home-assistant-aquarea/assets/48807086/4b8c98e7-e560-47e5-8543-ed53ebdbe212)

Again, thank you for the work you put into this

**Comment by cjaliaga** [comment] 2024-01-02 17:21
Hey @CofkoCof, I might have a theory. A couple of questions:

1) Does this happen every day every other hour?
2) Could you show me the consumption graph in the Panasonic app (https://aquarea-smart.panasonic.com/remote/a2wEnergyConsumption) for the same period and for the same consumption type?

Thanks!

**Comment by CofkoCof** [comment] 2024-01-02 18:16
Hi @cjaliaga,

- The missing values are always from the same time range (for example, I have values from 0:00-1:00, 2:00-3:00, 4:00-5:00,...), but I am missing values in range 1:00-2:00, 3:00-4:00,...)

- Attaching pictures for 31.12.2023 and 1.1.2024 from HA and Panasonic app

![2024-01-02_19h08_05](https://github.com/cjaliaga/home-assistant-aquarea/assets/48807086/f8e9aa76-796b-4f29-aae0-c995def2818b)
![2024-01-02_19h08_51](https://github.com/cjaliaga/home-assistant-aquarea/assets/48807086/ea61c1d0-d9d5-4fc9-83ca-c4ce6204bc7a)

![2024-01-02_19h07_52](https://github.com/cjaliaga/home-assistant-aquarea/assets/48807086/f652b3aa-e7b7-4499-b267-20735fd5ae26)
![2024-01-02_19h08_39](https://github.com/cjaliaga/home-assistant-aquarea/assets/48807086/f74d5f6c-b47a-42d7-bc8f-3b2ce278d6be)


Thank you

**Comment by superarturo15** [comment] 2024-01-03 10:48
Hi there, the same is happening to me

![Captura de pantalla 2024-01-03 114617](https://github.com/cjaliaga/home-assistant-aquarea/assets/144675763/35891c50-0c15-46b0-91b2-66d46540fc93)

![image](https://github.com/cjaliaga/home-assistant-aquarea/assets/144675763/1e6ede86-7911-402b-9d6b-8e6154ed241f)

**Comment by cjaliaga** [comment] 2024-01-07 12:49
Thanks @superarturo15 @CofkoCof. I'll add extra debug logs to the entities and release a new version with them as soon as possible. I'll let you know so you can install it, enable debug logging, let it run to reproduce the issue and share them.

Quick question for the time being: Are you still facing the issue on a regular basis?

**Comment by CofkoCof** [comment] 2024-01-07 14:36
@cjaliaga 
Yes, it happens every day. What is weird it that it seems to happen at almost the same hours (see screenshots for two days...the timing is almost the same)

**5.1.2024**
![2024-01-07_15h32_39](https://github.com/cjaliaga/home-assistant-aquarea/assets/48807086/3228a849-67b2-4665-a4c2-875cf0d84c63)
![2024-01-07_15h32_43](https://github.com/cjaliaga/home-assistant-aquarea/assets/48807086/5934ae47-d7c4-4b09-ad0d-219f345b6aaa)

**6.1.2024**
![2024-01-07_15h32_51](https://github.com/cjaliaga/home-assistant-aquarea/assets/48807086/c5438004-9ac5-4494-8b48-287a677cb0d0)
![2024-01-07_15h33_07](https://github.com/cjaliaga/home-assistant-aquarea/assets/48807086/5ec8b3d9-22e2-400a-81d1-035881d06492)

**Comment by superarturo15** [comment] 2024-01-09 16:42
@cjaliaga

The same in my case, the issue happens every day.

Thanks for your efforts.

**Comment by superarturo15** [comment] 2024-01-20 18:12
Hi there, Is there any problem with native aquarea cloud?, energy consumption hasn't appeared since last Wednesday,

**Comment by CofkoCof** [comment] 2024-01-21 09:04
I don't have that issues. It's still working the same as it was before.

But I did notice that when trying to open the Comfort Cloud app from phone, it asks for two-factor authentication. I didn't configure that because I am unsure if that breaks the integration.
Did you perhaps enable that?

**Comment by superarturo15** [comment] 2024-01-22 11:31
No, I didn't, The only thing what I did was to update a version that appeared on the Aquarea HACS integration last week. Anyone with same problem?.

**Comment by cjaliaga** [comment] 2024-01-22 14:26
@superarturo15 anything on the logs or any error in the entry configuration? Do you have polling enabled for the entry? Do you have updated data in the Panasonic webapp?

**Comment by superarturo15** [comment] 2024-01-22 17:16
no error in HA, with the las update, in fact appear other new options, as powerful o silent mode, that's amazing, but nor webapp neither HA have I energy statistics consumption data. Just tank and heating temperature.

**Comment by CofkoCof** [comment] 2024-01-22 17:24
If also web app doesnt have data, the issue is not in integrationA while ago I had to reset my aquarea network adapter…the link was reset due to power outageDont know about your setup, but I would check the adapter…on mine there was a STATUS light that wasnt glowing when I had the issue
    
  

 From: superarturo15 ***@***.***>Sent: Monday, January 22, 2024 6:16 PMTo: cjaliaga/home-assistant-aquarea ***@***.***>Cc: CofkoCof ***@***.***>; Mention ***@***.***>Subject: Re: [cjaliaga/home-assistant-aquarea] Missing consumption values for some hours (Issue #75) 
no error in HA, with the las update, in fact appear other new options, as powerful o silent mode, that's amazing, but nor webapp neither HA have I energy statistics consumption data. Just tank and heating temperature.

**Comment by superarturo15** [comment] 2024-01-24 17:02
> If also web app doesnt have data, the issue is not in integrationA while ago I had to reset my aquarea network adapter…the link was reset due to power outageDont know about your setup, but I would check the adapter…on mine there was a STATUS light that wasn't glowing when I had the issue

I don't think so, since I´ve got tank temperature from the app, thanks for your advice.

**Comment by CofkoCof** [comment] 2024-01-27 17:49
@cjaliaga @superarturo15
I solved my issue with the missing consumption. I changed the time zone to UTC + 1 in the Panasonic web app (before I had id it set to UTC + 0). After that, the issue was resolved

**Comment by cjaliaga** [comment] 2024-01-29 11:24
@CofkoCof these are great news, happy is finally working for you 😊 I'll see if I can add to the Wiki these troubleshooting steps and solution.

We use the timezone in the code (the one set on Home Assistant) to calculate the hour we're checking the consumption for and when the energy consumption for that hour is completed so we can jump to the next hour. It could make sense that if Home Assistant and Panasonic Cloud are not in sync, we see some discrepancies. 

Everything is a guess of course as I'd need to debug the code while the issue is happening to get the proper understanding.

I'll close this issue.

**Closed by cjaliaga** 2024-01-29 11:24 UTC

**Comment by superarturo15** [comment] 2024-01-29 12:18
> @cjaliaga @superarturo15 I solved my issue with the missing consumption. I changed the time zone to UTC + 1 in the Panasonic web app (before I had id it set to UTC + 0). After that, the issue was resolved

I'll check it out. Thanks @CofkoCof, @cjaliaga
